% plot time-frequency plot over trials for each subject, compeition + cooepration 
% check for variancey, plot significant one 
% to do: select inetrested channels 
clear all; close all; clc;
addpath('D:\software\fieldtrip-20190325');
addpath('D:\software\eeglab14_1_2b');
% load data/freqs.mat 
% load data/timepoints.mat
%% the first person each trial
trialNameSet ={'compet1_1','compet1_2','compet2_1','compet2_2','compet3_1','compet3_2',...
    'compet4_1','compet4_2','compet5_1','compet5_2','compet6_1','compet6_2',...
    'compet7_1','compet7_2','compet8_1','compet8_2','compet9_1','compet9_2',...
    'compet10_1','compet10_2','compet11_1','compet11_2','compet12_1','compet12_2','compet13_1','compet13_2',...
    'compet14_1','compet14_2','compet15_1','compet15_2','compet16_1','compet16_2',...
    'compet17_1','compet17_2','compet18_1','compet18_2','compet19_1','compet19_2',...
    'compet20_1','compet20_2','compet21_1','compet21_2','compet22_1','compet22_2',...
    'cooperation1_1','cooperation1_2','cooperation2_1','cooperation2_2','cooperation3_1','cooperation3_2',...
    'cooperation4_1', 'cooperation4_2','cooperation5_1', 'cooperation5_2',...
    'cooperation6_1', 'cooperation6_2','cooperation7_1', 'cooperation7_2',...
    'cooperation8_1', 'cooperation8_2','cooperation9_1', 'cooperation9_2',...
    'cooperation10_1', 'cooperation10_2','cooperation11_1', 'cooperation11_2',...
    'cooperation12_1', 'cooperation12_2','cooperation13_1', 'cooperation13_2',...
    'cooperation14_1', 'cooperation14_2','cooperation15_1', 'cooperation15_2',...
    'cooperation16_1', 'cooperation16_2','cooperation17_1', 'cooperation17_2',...
    'cooperation18_1', 'cooperation18_2','cooperation19_1', 'cooperation19_2'...
    'cooperation20_1', 'cooperation20_2','cooperation21_1', 'cooperation21_2',...
    'cooperation22_1', 'cooperation22_2','cooperation23_1', 'cooperation23_2',...
    'cooperation24_1', 'cooperation24_2','cooperation25_1', 'cooperation25_2'};

%%
for directI = 1:length(trialNameSet)
   clear EEG; EEG = pop_loadset(strcat(trialNameSet{directI},'.set'),'data/useful/');
   saveSubject('data/useful/',trialNameSet{directI},EEG.chanlocs);
end

function saveSubject(dicName,fileNameSet,chanLocs)
    load(strcat(dicName,fileNameSet,'_allitc.mat'),'allitc');
    min_allitc  = min(abs(allitc),[],'all');
    max_allitc = max(abs(allitc),[],'all');
    f = figure('visible','off');
     [freqsN,timesN,~] = size(allitc);
     freqs = 45/freqsN:45/freqsN:45;
     times = 15/timesN:15/timesN:15;
     tftopo(abs(allitc).^2,times(:,:,1),freqs(:,:,1),'mode','ave','limits',...
    [nan nan nan 45 nan nan],'chanlocs', chanLocs, 'cbar','on','title',fileNameSet);
    cbar('vert',0,[min(min_allitc) max(max_allitc)]); 
    saveas(f,strcat(dicName,'pic_2/',fileNameSet,'.png'));
    clear f;
end
