clear all;  close all; clc;
% calculate normalized and averaged spetral estimate 
% 1. normalize the lengths of each of te trial activity vectos to 1
% 2. cmpute their complex average over all epoches 
% calculated from eeglab  function pop_newtimef
%% for each person each trial, calculate time-frequency data
setList = {'compet1_1','compet1_2','compet2_1','compet2_2','compet3_1','compet3_2',...
    'compet4_1','compet4_2','compet5_1','compet5_2','compet6_1','compet6_2',...
    'compet7_1','compet7_2','compet8_1','compet8_2','compet9_1','compet9_2',...
    'compet10_1','compet10_2','compet11_1','compet11_2','compet12_1','compet12_2','compet13_1','compet13_2',...
    'compet14_1','compet14_2','compet15_1','compet15_2','compet16_1','compet16_2',...
    'compet17_1','compet17_2','compet18_1','compet18_2','compet19_1','compet19_2',...
    'compet20_1','compet20_2','compet21_1','compet21_2','compet22_1','compet22_2',...
    'cooperation1_1','cooperation1_2','cooperation2_1','cooperation2_2','cooperation3_1','cooperation3_2',...
    'cooperation4_1', 'cooperation4_2','cooperation5_1', 'cooperation5_2',...
    'cooperation6_1', 'cooperation6_2','cooperation7_1', 'cooperation7_2',...
    'cooperation8_1', 'cooperation8_2','cooperation9_1', 'cooperation9_2',...
    'cooperation10_1', 'cooperation10_2','cooperation11_1', 'cooperation11_2',...
    'cooperation12_1', 'cooperation12_2','cooperation13_1', 'cooperation13_2',...
    'cooperation14_1', 'cooperation14_2','cooperation15_1', 'cooperation15_2',...
    'cooperation16_1', 'cooperation16_2','cooperation17_1', 'cooperation17_2',...
    'cooperation18_1', 'cooperation18_2','cooperation19_1', 'cooperation19_2'...
    'cooperation20_1', 'cooperation20_2','cooperation21_1', 'cooperation21_2',...
    'cooperation22_1', 'cooperation22_2','cooperation23_1', 'cooperation23_2',...
    'cooperation24_1', 'cooperation24_2','cooperation25_1', 'cooperation25_2'};
for setI = 1:length(setList)
    EEG = pop_loadset(strcat(setList{setI},'.set'), 'data/useful');
    for elec = 1:EEG.nbchan
        [ersp,itc,~,times freqs,erspboot,itcboot] = pop_newtimef(EEG,...
        1, elec, [EEG.xmin EEG.xmax]*1000, [0.5 3],'baseline', [NaN], 'freqs',[1 45], 'padratio', 16, ... 
        'plotphase', 'off', 'timesout', 60, 'alpha', .05, 'plotersp','off', 'plotitc','off');
        if elec == 1  % create empty arrays if first electrode
            allersp = zeros([ size(ersp) EEG.nbchan]);
            allitc = zeros([ size(itc) EEG.nbchan]);
            allerspboot = zeros([ size(erspboot) EEG.nbchan]);
            allitcboot = zeros([ size(itcboot) EEG.nbchan]);
        end
        allersp (:,:,elec) = ersp;  % power then average over all epoches
        allitc (:,:,elec) = itc;    % normalized spectral esttimate (averaged over all epoches)
        allerspboot (:,:,elec) = erspboot; % significant value threshold 
        allitcboot (:,:,elec) = itcboot;
    end
    % Plot a tftopo() figure summarizing all the time/frequency transforms
    % figure;
    % tftopo(abs(allitc),alltimes(:,:,1),allfreqs(:,:,1),'mode','ave','limits',...
    %     [nan nan nan 45 nan nan],'chanlocs', EEG.chanlocs, 'cbar','on');
    % cbar('vert',0,[-1*min(abs(allitc),[],'all') 1*max(abs(allitc),[],'all')]);
    % tftopo(allersp,alltimes(:,:,1),allfreqs(:,:,1),'mode','ave','limits',...
    %     [nan nan nan 35 -1.5 1.5],'signifs', allerspboot, 'sigthresh', [6], 'timefreqs', ... 
    % [400 8; 350 14; 500 24; 1050 11], 'chanlocs', EEG.chanlocs);
    save('data/freqs.mat','freqs'); % run only once since it is the same for all trials
    save('data/times.mat','times'); % run only once since it is the smae for all trials
    save (strcat('data/useful/',setList{setI},'_allitc.mat'),'allitc');
    save (strcat('data/useful/',setList{setI},'_allitcboot.mat'),'allitcboot');
    save (strcat('data/useful/',setList{setI},'_allersp.mat'),'allersp');
    save (strcat('data/useful/',setList{setI},'_allerspboot.mat'),'allerspboot');
end
